default: &default

  api_options:
    # only return section items by default
    f:
      - category2|Index of Poets
    # sorting and response number
    sort:
      - date|asc
    num: 50
    # facet info on search page
    facet_limit: 20
    facet_sort: count|desc
    # facet info on browse page
    browse_sort: term|asc
    # highlighting
    hl_num: 5

  facets:
    en:
      title:
        label: Poet
      person_gender_k:
        label: Gender
        flags:
          - search_filter
      spatial.short_name:
        label: Country
        flags:
          - search_filter
      spatial.region:
        label: Region
        flags:
          - search_filter
      # NOTE the featured field will NEVER be searched
      # and all functionality is being overridden by the browse_facet
      # action
      featured:
        label: "Featured Poets"

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default

