default: &default

  api_options:
    # only return section items by default
    f:
      - subcategory|Index of Poets
    # sorting and response number
    sort:
      - date|asc
    num: 50
    # facet info on search page
    facet_limit: 20
    facet_sort: count|desc
    # facet info on browse page
    browse_sort: term|asc
    # highlighting
    hl_num: 5

  facets:
    en:
      person.name:
        label: Poet
      person.role:
        label: Gender
        flags:
          - search_filter
      places:
        label: Country
        flags:
          - search_filter
      keywords:
        label: Region
        flags:
          - search_filter
      # NOTE the featured field will NEVER be searched
      # and all functionality is being overridden by the browse_facet
      # action
      featured:
        label: "Featured Poets"

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default

