default: &default

  api_options:
    # only return section items by default
    f:
      - category|In the News
      - subcategory|Person (Poet)
    # sorting and response number
    sort:
      - date|asc
    num: 50
    # facet info on search page
    facet_limit: 20
    facet_sort: count|desc
    # facet info on browse page
    browse_sort: term|asc
    # highlighting
    hl_num: 5

  facets:
    en:
      person.name:
        label: Poet
        flags:
          - search_filter
      places:
        label: Nationality
        flags:
          - search_filter
      topics:
        label: Region
        flags:
          - search_filter
      source:
        label: News Items
        flags:
          - search_filter

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default

