default: &default

  api_options:
    # only return section items by default
    f:
      - category|Works
    # sorting and response number
    sort:
      - date|asc
    num: 50
    # facet info on search page
    facet_limit: 20
    facet_sort: count|desc
    # facet info on browse page
    browse_sort: term|asc
    # highlighting
    hl_num: 5

  facets:
    en:
      creator.name:
        label: Author
        flags:
          - search_filter
      topics:
        label: Decade
        flags:
          - search_filter
      date.year:
        label: Year
        flags:
          - search_filter
      citation.publisher:
        label: Publisher
        flags:
          - search_filter
      type:
        label: Publication Type
        flags:
          - search_filter

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default

