default: &default
  # If app should only be using a specific collection,
  # append "/collection/(collection_name)" to path
  api_path: https://cdrhdev1.unl.edu/api/v1
  # path to iiif server, NOT including the project directory
  iiif_path: https://cdrhmedia.unl.edu/iiif/2

  # IN THE NEWS CONFIG
  # elasticsearch settings to post / clear in the news records
  es_category: In the News
  es_collection: african_poetics
  es_index: index_name
  es_path: elasticsearch_posting_path

test:
  <<: *default

development:
  <<: *default
  api_path: https://cdrhdev1.unl.edu/api/v1
  iiif_path: https://cdrhdev1.unl.edu/iiif/2

production:
  <<: *default
  api_path: https://cdrhapi.unl.edu/v1
  iiif_path: https://cdrhmedia.unl.edu/iiif/2
